### ISSUE TITLE
can u show us the stress test result data ？

### ISSUE THREAD

**Issue by witskeeper** [ProxyKit/ProxyKit#103]
i saw this : “Stress testing shows that ProxyKit is approximately 8% slower than nginx for simple forwarding on linux”.

can u show the data about the stress testing ?

**Comment by damianh** [comment]
Yeah I need to back that up with some substance. I'll leave this open to follow up on. In the mean time I'm going to remove that statement until further proof because, on reflection, it shouldn't be there without it.

**Comment by witskeeper** [comment]
thanks for reply，and i will keep an eye on

**Comment by damianh** [comment]
Never got around to doing a formal benchmark and because of #230 I won't. However since Microsoft are building one in a similar fashion (kestrel -> middleware -> httpclient) for their Azure partners, it lends credence to the fact it'll be _fast enough_.
