### ISSUE TITLE
Parsing parameters for determining where to Proxy?

### ISSUE THREAD

**Issue by Tadimsky** [ProxyKit/ProxyKit#140]
Hey!

Is it possible to parse the parameters of the URL coming in and use that in order to determine where we should proxy the request to?
In our case, we store customer content in different geographies (EU, US, etc) and want to be able to pull out the parameters in the URL in order to determine where to proxy the request to.
We're currently using ProxyKit in our services directly and then have an action filter on each action which does this, but we'd like to decouple the proxying from our actual service and have ProxyKit sit in front of all of our API services.

For example, if our Route was `/users/{userId}/documents/{documentId}`, we'd want to be able to pull out `userId` and `documentId` and use that to determine where proxying should go.
We'd want it to use the same parameter matching logic that ASP.NET Core already has as that works well. We've tried doing our own but it's a little less reliable :).

Has anyone done something like this or does anyone know of a way to do this?

Thanks!

**Comment by clintnetwork** [comment]
Interesting, I would like to do something very close

**Comment by kattunga** [comment]
I have a similar problem.
I need to proxy to differents upstream servers depending on host request header.
I receive wildcard requests for a domain and proxy them to dynamically created containers.

Is possible to dynamically determine upstream server?

**Comment by damianh** [comment]
So moving to AspNetCore 3.1 and removing support for AspNetCore 2.1 (#200) we will be able to make use of endpoint routing to achieve this.

**Comment by Rohansi** [comment]
It's kind of possible already with ASP.NET Core 3.1. However it's not the best and lacks `async`.

```csharp
app.UseEndpoints(endpoints =>
{
    // ...

    var proxyApp = endpoints.CreateApplicationBuilder();

    proxyApp.UseWebSocketProxy(context =>
    {
        var ip = context.GetRouteValue("ip");
        var port = context.GetRouteValue("port");

        return new Uri($"ws://{ip}:{port}");
    });

    endpoints.Map("/proxy/{ip}/{port}", proxyApp.Build());

    // ...
});
```

**Comment by damianh** [comment]
Hi,

Thanks for sharing the wirk around. Due to #230 I won't be investing my time in improvements in this area. I'm going point you towards microsoft/reverse-proxy that will hopefully address your issue.

Cheers,

Damian
