### ISSUE TITLE
How To Modify Path of Forwarded Request?

### ISSUE THREAD

**Issue by andre259** [ProxyKit/ProxyKit#146]
I need to strip out one of the segments of the incoming request's path before forwarding. I'm not seeing any way to do this, it looks like whatever is on the incoming request's Path and QueryString are appended no matter what I do. Even if I completely re-write the entire Uri it still appends the incoming path.

I do notice i can add a prefix the outgoing path (which I don't need to do) via the UpstreamHost.PathBase, but the incoming request's path is still appended.

Is there any way to modify the incoming path?

**Comment by jnapier** [comment]
I have this same problem.  I would like to proxy a request to a different path than the incoming request.  The issue is that httpContext.ForwardTo uses the Path and Querystring from the originating request.  Many times this is the right choice but there are use cases where you need to direct the request to a different path.  

I thought that I would create my own instance of ForwardContext but it has an internal constructor.  I there anyway the constructor could be made public?  Or add an argument to httpContext.ForwardTo to not use the current requestPath only the values from UpstreamHost?

**Comment by andre259** [comment]
Maybe something like this?

**public static ForwardContext MyForwardTo(this HttpContext context, string uriString);**

and 

**public static MyForwardContext MyForwardTo(this HttpContext context, 
     string baseAddress, string path, string queryString = context.Request.QueryString);**

Where neither of these append the original path (like the existing method).

**Comment by jnapier** [comment]
I did this as a workaround for now.  It just modifies the upstream request uri to what i want.  Has the small overhead of constructing the upstream URI twice(once with the proxy kit code, then with my code).

```
public static ForwardContext ForwardTo(this HttpContext httpContext, UpstreamHost upstreamHost, PathString path, QueryString query) {

			//create the initial forward context with proxy kit
			ForwardContext forwardTo = httpContext.ForwardTo(upstreamHost);

			//the path and querystring on the forward context are from the httpContext,
			//this is not what the caller wants so we need to manipulate the uri
			var uri = new Uri(
		UriHelper.BuildAbsolute(
					upstreamHost.Scheme,
					upstreamHost.Host,
					upstreamHost.PathBase,
					path,
					query
				)
			);

			forwardTo.UpstreamRequest.RequestUri = uri;

			return forwardTo;
		} 
```

**Comment by andre259** [comment]
I ended up using something just like yours, jnapier, thanks! 

Hope they bake this is in someday, should be pretty straightforward.

**Comment by damianh** [comment]
@jnapier THat was the correct way. I've also added an override to `ForwardTo` to allow supplying your own upstream URI to prevent the additional allocation. This will probably be one of only a couple of API changes I'll make for the final major release.
