### ISSUE TITLE
Support rate limiting

### ISSUE THREAD

**Issue by damianh** [ProxyKit/ProxyKit#15]

**Comment by damianh** [comment]
Will consider porting this https://github.com/damianh/LimitsMiddleware

**Comment by vindberg** [comment]
Hi @damianh, have you considered porting your Limits middleware? We could use it :)

**Comment by damianh** [comment]
In light of #230 I'm not going to do this directly here. There are other rate limiting packages out there (i.e https://github.com/stefanprodan/AspNetCoreRateLimit) that fit the requirements and can work today. I also believe YARP will come with something out of the box.
