### ISSUE TITLE
Support passing CancellationToken to Send()

### ISSUE THREAD

**Issue by ben-foster-cko** [ProxyKit/ProxyKit#150]
We would like to pass a CancellationToken through to `ForwardContext.Send` so we can cancel a request after a certain period.

The use case is replaying the same request to a canary release and we want to ensure that we don't add too much overhead to the overall request i.e. if the canary doesn't work as expected, we can cancel the request.

I'm going to raise a separate issue regarding the sequential processing of the canary request.

**Comment by damianh** [comment]
Done. It has additional use case for timing out a requests.
