### ISSUE TITLE
Open investigation: CPU bumpiness

### ISSUE THREAD

**Issue by abergs** [ProxyKit/ProxyKit#155]
After upgrading from `2.0.4` to `2.1.3` I'm seeing a different CPU behavior.
![image](https://user-images.githubusercontent.com/357283/64962460-c8152100-d897-11e9-9aa1-1d52b440f132.png)

Have anyone else seen anything similar? I will do some loadtesting locally and try to profile to make sure the behavior is consistent. 

Just opening a ticket so that we can track the issue. It might turn out to be nothing, but the last ticket we did we found that thing in httpclientfactory so I thought it'll be worth it.

**Comment by damianh** [comment]
I'm wondering if it's because I'm allocating a new http client per request 🤔

**Comment by damianh** [comment]
In light of #230 I'm not going to invest any time in this and so closing. If anyone finds an issue for perf and submits a PR I will certainly consider it.
