### ISSUE TITLE
how to replace the href url of response text on using reverse proxy

### ISSUE THREAD

**Issue by wdf20** [ProxyKit/ProxyKit#161]

**Comment by damianh** [comment]
Do you wish to rewrite `<a href=".."` tags in responses? If so, do you also need to hand img, script and style `src`s?

The quick & answer is that you need to buffer the response, read it to a string, find-replace, and return the result to client. I'll try to put together an (experimental) recipe.

Thinking out loud - A more complicated but better performing answer (in terms of memory usage & response time) would be to do some sort of stream based processing on the html.

**Comment by damianh** [comment]
Personal note... how nginx does it: https://serverfault.com/questions/713148/modify-html-pages-returned-by-nginx-reverse-proxy

**Comment by barissaydag** [comment]
I would appreciate a recipe, too. How does one go about changing HTML content at all? What if the length changes? How will the content-length be calculated?

**Comment by damianh** [comment]
What ProxyKit basically does is:
1. Create an `HttpRequestMessage` (allowing you to customise)
2. forwards it to upstream host generating an `HttpResponseMessage` (allowing you to customise)
3. Maps `HttpResponse` to AspNet Core's `HttpResponse` (which you can customise in standard AspNetCore pipeline).

So we need to intercept 2. and generate new `HttpResponseMessage` from the upstream one with our rewritten content. 
I've started a recipe here that you can use today to get started: https://github.com/damianh/ProxyKit/blob/response-rewrite/src/ResponseRewrite/ProxyStartup.cs#L36 . This is just a start; the code is nowhere near as factored as I'd like it to be in order for it to included it as a core feature.

To make it a core feature there are a couple of challenges I want to address:
- handling compression (decompress all response? decompress-on-the-fly? recompress?)
- buffering the entire response (memory allocations) vs stream based rewriting (more complex)
- how it will work with response caching and CacheCow

**Comment by damianh** [comment]
I'm going to merge that recipe in as is. Any other improvements welcome as a PR.
