### ISSUE TITLE
Can't change the request path before WebSocket forward

### ISSUE THREAD

**Issue by nluyan** [ProxyKit/ProxyKit#177]
at WebSocketProxyMiddleware.cs
private Task ProxyOutToWebSocket(HttpContext context)
{
    var relativePath = context.Request.Path.ToString().TrimStart('/');
    var upstreamUri = _getUpstreamHost(context);
    var uriWithPath = new Uri(
        upstreamUri.Uri,
        relativePath.Length >= 0 ? relativePath : "");

    var uriBuilder = new UriBuilder(uriWithPath)
    {
        Query = context.Request.QueryString.ToUriComponent()
    };

    _logger.LogInformation("Forwarding websocket connection to {0}", uriBuilder.Uri);

    return AcceptProxyWebSocketRequest(context, uriBuilder.Uri);
}

if this line:
var upstreamUri = _getUpstreamHost(context);
move to above the:
var relativePath = context.Request.Path.ToString().TrimStart('/');
Will give proxykit to do some custom routing things ability by change context.Request.Path property at outside.
Could you modify this code please?
Thank you.

**Comment by damianh** [comment]
Hi,

Due to #230 I won't be investing my time in improvements in this area. I'm going point you towards microsoft/reverse-proxy that will hopefully address your issue.

- Damian
