### ISSUE TITLE
Can Proxykit intrgrate with Polly and HttpClientFactory

### ISSUE THREAD

**Issue by execution** [ProxyKit/ProxyKit#187]
Can we use polly : https://github.com/App-vNext/Polly  to create resilience and transient-fault-handling

**Comment by damianh** [comment]
Hi!

Firstly ProxyKit uses HttpClientFactory https://github.com/damianh/ProxyKit#24-configuring-proxykits-httpclient and you can configure it.

Regarding Polly and retries in general, this is something I'd like to see. However there are some challenges... ProxyKit is stream based and not message based for performance reasons - it doesn't buffer the incoming request to be able to forward it to another upstream host by default. If we were to attempt a retry we need to hook into the right places where this makes sense. I think being able to do a retry up to the point the headers are flushed to the upstream host could be achievable. Doing a retry when an error occurs _after_ that is a bit more complex.

Could you share any specific scenarios you have in mind where this would work for you?
