### ISSUE TITLE
Auto finished when proxy websocket to localhost

### ISSUE THREAD

**Issue by haptear** [ProxyKit/ProxyKit#190]
## To reproduce

1. start websocket server in localhost:88
2. create a mvc project, proxy websoket to localhost:88

## Expected behavior

The agent functions normally 

## Actual behavior

The current websocket agent will disconnect immediately upon success to localhost:88 

## Workarounds

chang the localhost to ip(127.0.0.1)  is work

**Comment by damianh** [comment]
I am not able reproduce this.

**Comment by haptear** [comment]
@damianh 
use the project https://github.com/haptear/TestProxyKit reproduce this.

**Comment by damianh** [comment]
Hi,

Sorry for delayed response.Du e to #230 I won't be investing my time in improvements in this area. I'm going point you towards microsoft/reverse-proxy that will hopefully address your issue.

Cheers,

Damian
