### ISSUE TITLE
A way to treat non-Success responses as Warnings

### ISSUE THREAD

**Issue by john--** [ProxyKit/ProxyKit#195]
## Use case(s)

When a proxied request fails (eg, returns an internal server error), I would like to see this in my logs as a warning or error.

## Description

To reduce noise I only log warnings and above.
When the forwarded request fails (eg, anything but 2XX level http codes), I would like to have an easy way to log it without having to drop my log level to info or create custom Logging filter. Currently it seems to log any response, regardless of the response code, at the info level. 

## Alternatives

Could potentially use NLog filtering to log the messages I'm interested in:

    <logger name="System.Net.Http.HttpClient.ProxyKitClient.*" minlevel="Info" writeTo="database">
      <filters>
        <when condition="ends-with('${message}','- OK') or not contains('${message}', 'End Processing')" action="Ignore" />
      </filters>
    </logger>

**Comment by damianh** [comment]
You can add your own logging by doing something like this:

```csharp
var response= await context
    .ForwardTo(_forwardTo)
    .AddXForwardedHeaders()
    .Send();

if(response.IsSuccessStatusCode)
{
	...log here...
}

return response;
```
