### ISSUE TITLE
Limited Proxy Handler Life-time

### ISSUE THREAD

**Issue by xsoheilalizadeh** [ProxyKit/ProxyKit#210]
## ProxyKit 2.3.0 on ASP.NET Core 3.1

Implement a typed `ProxyHanlder` and inject a scoped service inside its constructor:
```c#
public class ProxyHandler : IProxyHandler
{
    private IScopedService _scopedService;

    public ProxyHandler(IScopedService scopedService)
    {
        _scopedService = scopedService;
    }
}
```
```c#
services.AddSingleton<ProxyHandler>();
```
Alright we'll get the expected result:

```
Error while validating the service descriptor 'Service`
Type: App.ProxyHandler Lifetime: Singleton ImplementationType: 'App.ProxyHandler': Cannot consume scoped service 'App.IScopedService ' from singleton 'App.ProxyHandler'.
```

To resolve the issue we going to change the `ProxyHanlder` to scoped lifetime:

```c#
services.AddScoped<ProxyHandler>();
services.AddScoped<IProxyHandler,ProxyHandler>();
```
And again we'll face another issue:

```
 Cannot resolve scoped service 'App.ProxyHandler' from root provider.
```
This issue made by this [line](https://github.com/proxykit/ProxyKit/blob/master/src/ProxyKit/ProxyMiddleware.cs#L17) in the `ProxyMiddleware`. Only the singleton lifetime services are allowed to inject in a middleware constructor.

We could resolve this issue by injecting the `ProxyHanlder` in the `Invoke` method instead of the constructor.  

I could open a PR.

**Comment by xsoheilalizadeh** [comment]
I'll be happy if you consider this for v3.
@damianh

**Comment by damianh** [comment]
Am very late with response to this; life got in the way. I would like to see a PR if you still want to make an attempt for V3 (final major version).

**Comment by damianh** [comment]
Hi,


Sorry for slow response.

Due to #230 I won't be investing my time in improvements in this area. I'm going point you towards microsoft/reverse-proxy that will hopefully address your issue.

Cheers,

Damian
