### ISSUE TITLE
Proxykit doesn't handle content-length = null from test server

### ISSUE THREAD

**Issue by Erwinvandervalk** [ProxyKit/ProxyKit#213]
## Version(s)

2.3.0

## To reproduce

Failing test here
https://github.com/ProxyKit/ProxyKit/pull/212

## Expected behavior

Proxykit shouldn't skip sending the body if the content-length == null because the test host doesn't send the content-length. 

## Actual behavior

A recent change causes proxykit to no longer send the body if content length == null. 

https://github.com/ProxyKit/ProxyKit/blob/4468429f3910111b98d80821fd10824204573053/src/ProxyKit/HttpContextExtensions.cs#L56

Unfortunately, the test server doesn't send the content length so all my tests with a body start failing. 

## Workarounds

Adding this in the proxy method works in 2.1, but doesn't seem to work in higher versions. 

                if (context.Request.Method != "GET" && context.Request.ContentLength == null)
                {
                    // Hack: content length is not always set correctly when sending requests from test server
                    context.Request.ContentLength = context.Request.Body?.Length;
                }

**Comment by damianh** [comment]
Fixed
