### ISSUE TITLE
Can you reverse proxy YouTube?

### ISSUE THREAD

**Issue by bbhxwl** [ProxyKit/ProxyKit#215]
Can you reverse proxy YouTube?

**Comment by damianh** [comment]
You can try but doubt it will work well. ProxyKit is a reverse proxy, you probably want a [forward proxy](https://www.jscape.com/blog/bid/87783/Forward-Proxy-vs-Reverse-Proxy).

**Comment by bbhxwl** [comment]
> You can try but doubt it will work well. ProxyKit is a reverse proxy, you probably want a [forward proxy](https://www.jscape.com/blog/bid/87783/Forward-Proxy-vs-Reverse-Proxy).

I use it in China. I have used nginx instead of Google. China can't use it directly. I don't want to use proxy IP. It's not stable. I want to use anti generation technology, except nginx. Anti YouTube seems to involve many different domain names, which is a little complicated

**Comment by damianh** [comment]
Reverse proxies are for use on internal networks. You need a forward proxy.

**Comment by bbhxwl** [comment]
> Reverse proxies are for use on internal networks. You need a forward proxy.

I know that I can use nginx to implement reverse proxy websites, because China can't directly use these websites and doesn't want to use forward proxy. Some devices can't use proxy IP software, so I want to use reverse proxy. I think proxykit should be able to replace nginx. Implement reverse proxy and make some restrictions.
