### ISSUE TITLE
Is there a demo for reverse proxy HTTP?

### ISSUE THREAD

**Issue by bbhxwl** [ProxyKit/ProxyKit#216]
Is there a demo for reverse proxy HTTP?

I use the following code to execute after app.useendpoints. There is no response. Before that, there will be 502 errors

  app.RunProxy(context => context
         .ForwardTo("http://baidu.com")
         .AddXForwardedHeaders()
         .Send());

**Comment by damianh** [comment]
I've already told you that ProxyKit is for [reverse proxies](https://en.wikipedia.org/wiki/Reverse_proxy). It is not designed nor supported for what you are trying to do.
