### ISSUE TITLE
Who can help to see what code to use instead of this nginx configuration?

### ISSUE THREAD

**Issue by bbhxwl** [ProxyKit/ProxyKit#218]
How to modify the proxy set header of nginx, and what to replace in the proxy kit? How else can I modify the proxy cookie domain? Thank you for your help.

server {
    listen       80;
    server_name   365google.com;
    location / {
     proxy_pass https://www.google.com;
    proxy_http_version 1.1;
 # 替换指定字符串
            sub_filter                          www.google.com 365google.com;
            # 字符串只进行一次替换，即只替换第一个被匹配的字符串。这里关闭。
            sub_filter_once                     off;

            # 指定头部：
            proxy_set_header  Host              "www.google.com";
            proxy_set_header  Referer           $http_referer;
            proxy_set_header  X-Real-IP         $remote_addr;
            proxy_set_header  User-Agent        $http_user_agent;
            # 防止谷歌返回压缩的内容，因为压缩的内容无法替换字符串
            proxy_set_header  Accept-Encoding   "";

            #把 cookie 的作用域替换成你的域名
            proxy_cookie_domain                 www.google.com 365google.com;
            #传固定的 cookie 给谷歌，是为了禁止即时搜索，因为开启即时搜索无法替换内容
            proxy_set_header  Cookie           "PREF=ID=047808f19f6de346:U=0f62f33dd8549d11:FF=2:LD=en-US:NW=1:TM=1325338577:LM=1332142444:GM=1:SG=2:S=rE0SyJh2W1IQ-Maw";

    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

**Comment by damianh** [comment]
ProxyKit is for reverse proxies. You need a forward proxy.
