### ISSUE TITLE
502 Bad Gateway - Azure

### ISSUE THREAD

**Issue by markgould** [ProxyKit/ProxyKit#219]
Looks like problem #179 has resurfaced in 2.3.2. It works in 2.3.0

This commit appears to have done it: 
https://github.com/ProxyKit/ProxyKit/commit/09505c720fcae06fb08c4e50ddb23ddcd7fbabc3#diff-7ae9aa92fe8fba004ba2b80d2ee04852

I'd be happy to help try and come up with a resolution. For now I've downgraded to 2.3.0.

**Comment by markgould** [comment]
If there is no Content-Length header (or it's zero) and also no Transfer-Encoding header then it looks like it should be safe to say there is no body.

I noticed in the master 3.0 branch it still has it the old way (Checking for content length). Do you have plans for how that will work in 3.0 right now?

**Comment by pksorensen** [comment]
I ran into this and never left 2.1.3 version either. I remember there were some other issues on the topic also. Will try to find out the status.

**Comment by pksorensen** [comment]
Ahh you found it yourself, https://github.com/ProxyKit/ProxyKit/issues/179. I did not know its been fixed and then broken again. guess i can go to 2.3.0 then :)

**Comment by jj707** [comment]
Is there a horizion on when that bug is fixed? Maybe you should withdraw the 2.3.2 version?

Regards :)

**Comment by damianh** [comment]
Been very busy recently, will try to get to this soon. In the mean time, the workaround is to use 2.3.0.

Thanks for your patience.

**Comment by damianh** [comment]
Been investigating this this evening.

> If there is no Content-Length header (or it's zero) and also no Transfer-Encoding header then it looks like it should be safe to say there is no body.

Yes, according to RFC2161 https://tools.ietf.org/html/rfc2616#section-4.3 this would be the correct approach. I've opened PR #227 to address this. Howver, I was leaning heavily on ASP.NET Core's TestSever in the process found a bug with it that may affect people: https://github.com/dotnet/aspnetcore/issues/21677

> I noticed in the master 3.0 branch it still has it the old way (Checking for content length). Do you have plans for how that will work in 3.0 right now?

There has been maintenance work on 2.x. branch that will be backported so v3 is behind at the moment.

**Comment by damianh** [comment]
Something to be wary of: https://github.com/dotnet/aspnetcore/issues/19541#issuecomment-600843456

**Comment by damianh** [comment]
Fixed regression as part of #227.

Package on nuget.org https://www.nuget.org/packages/ProxyKit/2.3.3
