### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by leastprivilege** [ProxyKit/ProxyKit#223]
I heard Microsoft are now finally working on a reverse proxy. This will be much better - and faster.

:p

**Comment by isaacabraham** [comment]
Exactly right! Plus, their one also has an [IRandomFactory](https://github.com/microsoft/reverse-proxy/blob/master/src/ReverseProxy.Utilities/Utils/IRandomFactory.cs) which looks cool, and Unit, Result and Option classes. It's true that the Option one [is also called Result](https://github.com/microsoft/reverse-proxy/blob/master/src/ReverseProxy.Core/Abstractions/Misc/Result.cs) , but we can't have everything - main thing is it has functional programming stuff in it so for religious reasons we must all move over immediately.

**Comment by damianh** [comment]
lol 😄  

oh well...

On a serious note, will keep things maintained at least until the other one is released. So yeah, it'll be dead in due course.

**Comment by damianh** [comment]
So.. the real answer is that it will be https://github.com/ProxyKit/ProxyKit/issues/230
