### ISSUE TITLE
Drop TestServer

### ISSUE THREAD

**Issue by damianh** [ProxyKit/ProxyKit#228]
I've had a number of issues with AspNet Core's TestServer. For example:

https://github.com/dotnet/aspnetcore/issues/18463
https://github.com/dotnet/aspnetcore/issues/21677

Essentially it's not HTTP spec compliant and has edge cases that make it different from Kestrel that I run into.

Going to drop support for it, remove it from tests and generally discourage usage.

**Comment by bklooste** [comment]
Its a bad testing model as well as your testing config and build.

**Comment by damianh** [comment]
It appears they fixed both of these issues as well as a couple more because they ran into them when they made their own reverse proxy 😬 .NET OSS is frustrating sometimes.
