### ISSUE TITLE
Run on dedicated endpoint

### ISSUE THREAD

**Issue by bbodenmiller** [ProxyKit/ProxyKit#229]
Is it possible to run this on a dedicated endpoint? How about using URL parameter as `ForwardTo`?

For example

myapp.com and myapp.com/api/books serves my content but myapp.com/proxy/google.com proxies google.com, myapp.com/proxy/anywebsite.com proxies anywebsite.com, etc.

**Comment by damianh** [comment]
It's possible to work with url parameters with endpoint routing, see this comment: https://github.com/ProxyKit/ProxyKit/issues/140#issuecomment-618719239

I don't really understand what you mean by "run this on a dedicated endpoint".

**Comment by damianh** [comment]
`myapp.com/proxy/google.com`

Just to say, this project is a reverse proxy and not designed for forwarding to public websites.
