### ISSUE TITLE
ProxyKit, YARP and planned obsolescence.

### ISSUE THREAD

**Issue by damianh** [ProxyKit/ProxyKit#230]
Microsoft have announced YARP, their [reverse proxy toolkit](https://devblogs.microsoft.com/dotnet/introducing-yarp-preview-1/) with initial release planned for around same time as .NET 5. To be honest, with a lot of focus on performance, networking, protocols etc, it is such an obvious thing to build that I'm actually suprised it took this long. Also, the direction of being a code-first toolkit validates the idea and need for such an approach. In the end, Microsoft will be able to do things to the framework/runtime to better facilitate a solution that ProxyKit can't.

In light of this, the plan for ProxyKit is:

1. ~Do one last major release for .NET Core 3.1. with couple of new features.~ _This didn't happen, there won't be a major new release._
2. Maintain support (bug fixes only) for the duration of .NET Core 3.1 LTS.
3. Shut it down and archive at end of .NET Core 3.1 LTS support.

On a personal level, I'm fine with this as it'll be less for me to maintain in the long run while having a solution that works for me and many others right now and in future. @samsp-msft and team did reach out to me before public announcement so it wasn't a surprise and which I appreciate.

Thanks for your support.

**Comment by jkonecki** [comment]
Thank you for this update and for running this project. As an active user of ProxyKit I understand and support your decision.

**Comment by damianh** [comment]
I've just published a patch release that I expect to be the last release. Since YARP has decided to also support ASP.NET Core 3.1, and with (I expect) a release with .NET 5.0, I decided it wasn't worth investing my time in a new major version. Apologies to those of you that created issues that would have resulted in improvements and were left waiting.

Cheers.
