### ISSUE TITLE
Incorrect forwarding of multiple cookies

### ISSUE THREAD

**Issue by ocdi** [ProxyKit/ProxyKit#231]
## Version(s)

`2.3.3`

## To reproduce

A PR with either a failing test or modification of one the runnable samples that
clearly demonstrates the problem is preferred. If this is not possible clearly
outline the steps to reproduce the behavior:

0. Create AspNetCore 3.1 Empty project
1. Create a basic proxy `app.RunProxy(async ctx => ctx.ForwardTo(upstream)).AddXForwardedHeaders()`
2. Have an upstream that will have multiple cookies
3. The cookies are sent with `,` instead of `;` by default

## Expected behavior

Cookies are sent in the expected behaviour. Because they have a , the cookies are not parsed correctly and this causes issues.

## Actual behavior

The cookie is parsed as a single value on the other end.

## Workarounds

I solved this by manually modifying the upstream request. It appears that the AspNetCore middleware must parse the cookie into many values, which when using a request is useful, but since we are blindly forwarding them, it ends up with multiple separate Cookie headers, which are automatically joined with a , on the other end.

I was able to work around this by explicitly grabbing the cookies and re-join them in a single value.

The fact I needed to add this code didn't meet my expectations, but I could also be doing something wrong. 

```c#
var proxyReq = ctx.ForwardTo(upstream).AddXForwardedHeaders();

if (proxyReq.UpstreamRequest.Headers.TryGetValues("Cookie", out var cookies))
{
    proxyReq.UpstreamRequest.Headers.Remove("Cookie");
    proxyReq.UpstreamRequest.Headers.Add("Cookie", string.Join(";", cookies));
}
```

## Additional context

Note this did work fine if I had only a single cookie for the request. In my case I am forwarding to an older ASP.NET MVC 5 application, attempting to use ProxyKit as a strangler to slowly migrate to AspNetCore. The issue I had was the __RequestValidationToken worked fine on dev, but on our test deploy we have GA enabled which added the GA cookies to the request.

**Comment by damianh** [comment]
Looks like MS experienced the same issue:
- https://github.com/microsoft/reverse-proxy/pull/451
- https://github.com/dotnet/aspnetcore/issues/26461

**Comment by damianh** [comment]
I've attempted to reproduce the issue with some functional tests in #243 however I am not able reproduce.

The incoming headers look good in raw form (there is a seperate `request.Cookies` that splits them out):

![image](https://user-images.githubusercontent.com/57436/96992860-c0a85880-152a-11eb-8b1a-6b770ce3bc85.png)

The outgoing cookie header looks good:

![image](https://user-images.githubusercontent.com/57436/96993119-25fc4980-152b-11eb-93c2-db46b84b3ccc.png)

Is there something I'm missing here?

**Comment by damianh** [comment]
Ok I think I am on to something. I'm using HTTPClient in my tests and I can't send individual `Cookie` headers - they are always concatenated with a `,`.

According to https://stackoverflow.com/questions/16305814/are-multiple-cookie-headers-allowed-in-an-http-request , having multiple `Cookie` headers in a HTTP/1.1 is invalid. If you have a client that is sending such requests it is probably misbehaving (and probably why there have not been more reports of this).

However in HTTP/2.0, multiple cookie headers are allowed so I'll port the fix from YARP.

**Comment by damianh** [comment]
Ported.
