### ISSUE TITLE
Is it possible to create end-point along proxying request to upstream services. 

### ISSUE THREAD

**Issue by ram62836** [ProxyKit/ProxyKit#233]
Hi Team,

Is to possible to build a service, forwarding requests to upstream service as well as have it own end-points?

/serviceA -> route the requests to serviceA
/serviceB -> route the requests to serviceB
/bff-endpoint -> route to the app end-points within BFF service

**Comment by damianh** [comment]
Yes. See https://github.com/ProxyKit/Recipes#2-proxy-paths
