### ISSUE TITLE
How to set proxy IP with webapi in upstream request?

### ISSUE THREAD

**Issue by paysen-z** [ProxyKit/ProxyKit#236]
>         
           var handler = new HttpClientHandler
            {
                AllowAutoRedirect = true,
                UseCookies = true
            };
            if (CurrentIp != null)
            {
                handler.Proxy = new WebProxy($"http://{CurrentIp.IP}:{CurrentIp.Port}");
            }

**Comment by damianh** [comment]
Configure the primary handler via HttpClientFactory : https://github.com/ProxyKit/ProxyKit#24-configuring-proxykits-httpclient

**Comment by paysen-z** [comment]
Thanks,but i want to set up dynamic proxy ip with the webapi.
It's multiple, not single,and it's not a fixed ip.
