### ISSUE TITLE
ForwardTo to a VPN with NetworkCredentials?

### ISSUE THREAD

**Issue by vindberg** [ProxyKit/ProxyKit#237]
Hi, im trying to tunnel requests to a VPN service that needs network credentials (username, password).

Im getting a popup window to enter the credentials with the current solution that looks like this:

```           
            var proxy = new WebProxy
            {
                Address = new Uri($"http://{proxyHost}:80"),
                BypassProxyOnLocal = false,
                UseDefaultCredentials = false,


                // *** These creds are given to the proxy server, not the web server ***
                Credentials = new NetworkCredential(
                    userName: "***",
                    password: "***"
                )
            };

            var httpClientHandler = new HttpClientHandler
            {
                Proxy = proxy,
            };

            services.AddProxy(httpClientBuilder =>
                httpClientBuilder.ConfigurePrimaryHttpMessageHandler(() => httpClientHandler));
```

Configure looks like this:

```
            var upstreamHost = new UpstreamHost($"http://{proxyHost}:80/");
            app.RunProxy(context => context
                .ForwardTo(upstreamHost)
                .CopyXForwardedHeaders()
                .AddXForwardedHeaders()
                .Send());
```

Im using Firefox to proxy all requests to this proxykit dotnet service which works. However, the credentials are not added to the tunnel to the vpn so the browser asks for it.

Any ideas are most welcome. Im running out of options.
Best,
Anders

**Comment by damianh** [comment]
I have a suspicion you may need to strip out authorization header on the upstream response so it doesn't return to your browser. To be honest, tunnelling to a VPN service is not a scenario I envisaged in usual reverse proxying circumstances so I'm not going to explore any further. The code is there for you to take and try to get it working for whatever you are trying to do.
