### ISSUE TITLE
How to proxy requests with routing to controllers?

### ISSUE THREAD

**Issue by Ibrahim-Islam** [ProxyKit/ProxyKit#238]
E.g. It will POST to my endpoint at `/api/data` and then from the controller I can proxy the request to upstream server and return the result in response.

**Comment by damianh** [comment]
Hi,

Sorry for slow response.

Due to #230 I won't be investing my time in improvements in this area. I'm going point you towards microsoft/reverse-proxy that will hopefully address your issue. Their implementation has an `IHttpProxy` that you can inject into your controller.

Cheers,

Damian
