### ISSUE TITLE
ConsulServiceDiscovery with dynamic services

### ISSUE THREAD

**Issue by nicstrong** [ProxyKit/ProxyKit#34]
Great work on this project, thanks!

I am using a slight variation on the ConsulServiceDiscovery recipe. Except in my case the upstream services are more dynamic in that they can be added at runtime without code change (the application proxy also has registration APIs).

Because I can't spin up a proxy per service with `IApplicationBuilder.Map()` I can't get the middleware to set to strip the proxy part of the path out of `Request.Path` so it doesn't get forwarded to upstream services. E.g. `/api/foo/some/api/resource` needs to be forwarded on as `/some/api/resource`. I work around this by rewriting `Request.Path` with the stripped path. Was wondering if maybe the `UpstreamHost` would be a better place to capture this?

More of a discussion than issue, so feel free to close.

**Comment by damianh** [comment]
The `.Map()` is really only for simple (path base) scenarios or where you want to have different proxies that have different core configurations. Rewriting the `ForwardContext.UpstreamRequest.Path` is right way to go and the workaround is reasonable. However I think we could make it more user friendly, i.e. being able to define rewrite rules. Leaving this open while I think think of what this could look like and as a place for you and others to make suggestions.

**Comment by damianh** [comment]
This was added [as a recipe](https://github.com/ProxyKit/Recipes/#9-consul-service-discovery) some time ago.
