### ISSUE TITLE
ForwardTo Uri is incorrect when using .MapWhen()

### ISSUE THREAD

**Issue by vascofernandes** [ProxyKit/ProxyKit#66]
Thanks for the cool project. Very useful.

I am loading proxy maps from a config file like this:

````json
"UrlMaps": [
        {
            "path": "/sysa",
            "target": "https://localhost:5001/sysatest/",
            "workerName": "sys1-worker"
        },
        {
            "path": "/sysb",
            "target": "https://localhost:5001/sysbtest/",
            "workerName": "sys2-worker"
        },
        {
            "path": "/sysc",
            "target": "https://localhost:5001/sysctest/",
            "workerName": "sys3-worker"
        }
    ]
````

Then in my Startup.cs I do:
````csharp
app.MapWhen(context => knownPaths.Contains(context.Request.Path), appInner =>
{
	appInner.RunProxy(context =>
	{
		var targetUrl = urlMaps[context.Request.Path];

		return context
			.ForwardTo(targetUrl)
			.AddXForwardedHeaders()
			.Send();
	});
});
````
The problem:

When I hit /sysb I would expect to be forwarded to https://localhost:5001/sysbtest/.
What actually happens is that I am forwarded to https://localhost:5001/sysbtest/sysb.

According to the docs: [aspnet/core/fundamentals/middleware
](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2)

> When Map is used, the matched path segment(s) are removed from HttpRequest.Path and appended to HttpRequest.PathBase for each request.

The problem is here:

[ProxyContextExtensions.cs#L24](https://github.com/damianh/ProxyKit/blob/master/src/ProxyKit/ProxyContextExtensions.cs#L24)

So when you use .Map() the HttpRequest.Path is "" and everything works ([ApplicationBuilderExtensions.cs#L54](https://github.com/damianh/ProxyKit/blob/master/src/ProxyKit/ApplicationBuilderExtensions.cs#L54))

But that is not the case with .MapWhen(), HttpRequest.Path is not empty and the path is appended to the target url.

I can just do `context.Request.Path = "";` before calling the `.Send()`, but it feels less than ideal :)

**Comment by damianh** [comment]
Thanks for the report and detailed description. Sorry for delay, been very busy.

I can confirm your observations. I don't have an answer yet, need to analyse it a bit more. Apply the workaround for now.

**Comment by damianh** [comment]
I've noticed that it's not possible to map with a trailing slash either (i.e. `.Map("/sync/")`) so to fix this I think I am going to have to avoid using  `.Map()` which will (breaking-) change things. In doing so, it should address this issue at same time.

**Comment by damianh** [comment]
Yeah this has been sitting around for a while and looked back into it again when I came across this https://stackoverflow.com/a/55080134

> The accepted answer is helpful, but not entirely accurate. Apart from the predicate logic, key differences between Map and MapWhen are that Map will add MapMiddleware to the pipeline (see here), while MapWhen will add MapWhenMiddleware to the pipeline (see here). The effect of this is that Map will update the Request.Path and Request.PathBase to account for branching based on path (trimming the matched path segment off Request.Path and appending it to Request.PathBase), while a seemingly equivalent MapWnen predicate will not. This affects anything downstream that uses the path, such as routing!

So `MapWhen` has a behaviour difference to `Map` that ProxyKit leveraged. 

Found out the reason why this is. From https://github.com/dotnet/aspnetcore/issues/3762#issuecomment-434474516: 

> From the doc: "MapWhen branches the request pipeline based on the result of the given predicate." It's not branching based on path, it's an arbitrary condition. That means it's not possible for it to take any secondary actions like modifying the path.

Good news is it looks like this is [going to be addressed](https://github.com/dotnet/aspnetcore/pull/15364) in .NET 5. What I will minimally do for ASP.NET COre 3.1 is to document this and will consider add custom middleware that has the same behavior as the .NET5 one.

**Comment by damianh** [comment]
> I've noticed that it's not possible to map with a trailing slash either (i.e. .Map("/sync/")) so to fix this I think I am going to have to avoid using .Map() which will (breaking-) change things. In doing so, it should address this issue at same time.

I believe this will be addressed using endpoint routing which can be used in conjuntion with .Map()

**Comment by damianh** [comment]
Hi,

Due to #230 I won't be investing my time in improvements in this area. I'm going point you towards microsoft/reverse-proxy that will hopefully address your issue.

Cheers,

Damian
